import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/shared/NavMenu";
import Header from "@/components/homePage/Header";
import HowItWorks from "@/components/homePage/HowItWorks";
import HowHelp from "@/components/homePage/HowHelp";
import Contact from "@/components/homePage/Contact";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });
import axios from "axios";

export default function Home() {
  axios.get("https://sitandlipapi.onrender.com/api/v1/profileManagement/client/22").then((res)=>console.log(res))
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <NavBar />
        <Header/>
        <HowItWorks/>
        <HowHelp/>
        <Contact/>
        <Footer/>
        {/* <h1>welcome to next</h1> */}
      </main>
    </>
  );
}
